env:
  browser: true
  es2021: true
  jest/globals: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:eslint-comments/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:jest/recommended
  - plugin:jest/style
  - prettier
plugins:
  - "@typescript-eslint"
  - import
  - jest
overrides:
  [
    {
      files: ["**/*.test.ts"],
      extends: ["plugin:jest/recommended"],
      plugins: [jest],
      rules: { "jest/prefer-expect-assertions": "off" },
    },
  ]
rules:
  {
    "@typescript-eslint/no-unused-vars": "error",
    "@typescript-eslint/consistent-type-definitions": ["error", "type"],
  }
